import React,{useMemo,useState}from'react';import{createRoot}from'react-dom/client';import{Menu,Search,ShoppingCart,MapPin,Plus,Minus,X,ChevronRight,ArrowLeft,Trash2,Home,Grid2X2,Heart}from'lucide-react';import'./style.css';
const cats=['Hamburguesas','Completos','Papas','Bebidas','Promos'];
const data=[
{id:1,cat:'Hamburguesas',name:'Clásica',desc:'Carne, queso cheddar, lechuga, tomate, cebolla y salsa de la casa.',price:6500,img:'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=700&q=90'},
{id:2,cat:'Hamburguesas',name:'Doble',desc:'Doble carne, doble queso, lechuga, tomate, cebolla y salsa de la casa.',price:8500,img:'https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=700&q=90'},
{id:3,cat:'Hamburguesas',name:'Bacon',desc:'Carne, queso cheddar, tocino crujiente, cebolla crispy y salsa BBQ.',price:7900,img:'https://images.unsplash.com/photo-1594212699903-ec8a3eca50f5?auto=format&fit=crop&w=700&q=90'},
{id:4,cat:'Hamburguesas',name:'Especial',desc:'Carne, queso, tocino, huevo, lechuga, tomate, cebolla y salsa de la casa.',price:8900,img:'https://images.unsplash.com/photo-1571091718767-18b5b1457add?auto=format&fit=crop&w=700&q=90'},
{id:5,cat:'Completos',name:'Completo Italiano',desc:'Vienesa, tomate, palta y mayo.',price:4500,img:'https://images.unsplash.com/photo-1612392062631-94dd858cba88?auto=format&fit=crop&w=700&q=90'},
{id:6,cat:'Completos',name:'Completo Dinámico',desc:'Vienesa, tomate, palta, mayo y mostaza.',price:4500,img:'https://images.unsplash.com/photo-1612392062631-94dd858cba88?auto=format&fit=crop&w=700&q=90'},
{id:7,cat:'Completos',name:'Completo Chacarero',desc:'Vienesa, tomate, palta, porotos verdes y mayo.',price:4800,img:'https://images.unsplash.com/photo-1612392062631-94dd858cba88?auto=format&fit=crop&w=700&q=90'},
{id:8,cat:'Papas',name:'Papas Grandes',desc:'Papas fritas doradas y crujientes.',price:3500,img:'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?auto=format&fit=crop&w=700&q=90'},
{id:9,cat:'Papas',name:'Papas Cheddar',desc:'Papas crujientes con cheddar.',price:4000,img:'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?auto=format&fit=crop&w=700&q=90'},
{id:10,cat:'Bebidas',name:'Bebida en lata',desc:'Elige tu sabor disponible.',price:2000,img:'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&w=700&q=90'},
{id:11,cat:'Promos',name:'Combo',desc:'Hamburguesa + papas + bebida.',price:9900,img:'https://images.unsplash.com/photo-1594212699903-ec8a3eca50f5?auto=format&fit=crop&w=700&q=90'}];
const money=n=>'$'+n.toLocaleString('es-CL');
function App(){const[screen,setScreen]=useState('intro'),[cat,setCat]=useState('Hamburguesas'),[q,setQ]=useState(''),[cart,setCart]=useState({}),[selected,setSelected]=useState(null),[note,setNote]=useState('');
const add=(id,e)=>{e?.stopPropagation();setCart(c=>({...c,[id]:(c[id]||0)+1}))},sub=(id,e)=>{e?.stopPropagation();setCart(c=>({...c,[id]:Math.max(0,(c[id]||0)-1)}))};
const count=Object.values(cart).reduce((a,b)=>a+b,0),subtotal=data.reduce((s,p)=>s+(cart[p.id]||0)*p.price,0),delivery=count?2000:0,total=subtotal+delivery;
const filtered=useMemo(()=>data.filter(p=>(screen==='search'||p.cat===cat)&&(!q||p.name.toLowerCase().includes(q.toLowerCase())||p.desc.toLowerCase().includes(q.toLowerCase()))),[cat,q,screen]);
if(screen==='intro')return <div className="intro introExact"><img src="/intro-cover.jpg" alt="'Onde el Chucky Street Food"/><button className="introHotspot" aria-label="Comenzar" onClick={()=>setScreen('home')}></button></div>;
if(screen==='promos')return <Shell screen={screen} setScreen={setScreen} count={count}><div className="darkScreen"><h1>Promociones</h1><p>MÁS SABOR, MÁS PLANES</p>{data.filter(x=>x.cat==='Promos').concat(data.filter(x=>x.cat==='Papas').slice(0,1)).map(p=><article className="promoCard"><img src={p.img}/><div><b>{p.name.toUpperCase()}</b><span>{p.desc}</span><strong>{money(p.price)}</strong></div><button onClick={e=>add(p.id,e)}><Plus/></button></article>)}</div></Shell>;
if(screen==='search')return <Shell screen={screen} setScreen={setScreen} count={count}><div className="darkScreen searchScreen"><h1>Buscar</h1><p>ENCUENTRA TU ANTOJO</p><label><Search/><input autoFocus value={q} onChange={e=>setQ(e.target.value)} placeholder="Buscar..."/></label>{filtered.map(p=><ProductRow p={p} add={add} setSelected={setSelected}/>)}</div></Shell>;
if(screen==='cart')return <Cart cart={cart} data={data} add={add} sub={sub} note={note} setNote={setNote} subtotal={subtotal} delivery={delivery} total={total} setScreen={setScreen}/>;
return <Shell screen={screen} setScreen={setScreen} count={count}><header className="top"><button><Menu/></button><div className="brand"><strong>'ONDE EL CHUCKY</strong><span>STREET FOOD</span></div><button onClick={()=>setScreen('cart')} className="cartIcon"><ShoppingCart/>{count>0&&<i>{count}</i>}</button></header><main className="home">
<div className="meta"><div><MapPin/><p><b>San Javier</b><small>Retiro y delivery</small></p></div><div className="open"><span/> <p><b>Abierto</b><small>12:00 - 23:30</small></p></div></div>
<label className="homeSearch" onClick={()=>setScreen('search')}><Search/><span>Buscar en el menú...</span></label>
<nav className="catIcons">{cats.map(c=><button onClick={()=>{setCat(c);setScreen('menu')}} className={cat===c?'active':''}><span>{c==='Hamburguesas'?'🍔':c==='Completos'?'🌭':c==='Papas'?'🍟':c==='Bebidas'?'🥤':'%'}</span><small>{c}</small></button>)}</nav>
{screen==='home'&&<><section className="promoBanner" onClick={()=>setScreen('promos')}><div>PAPAS GRANDES<br/><em>GRATIS</em><small>En compras sobre $15.000</small></div><img src={data[8].img}/></section><div className="sectionTitle"><h2>Lo más pedido</h2><button onClick={()=>setScreen('menu')}>Ver todo →</button></div><div className="popular">{[data[0],data[7]].map(p=><article onClick={()=>setSelected(p)}><img src={p.img}/><b>{p.name}</b><strong>{money(p.price)}</strong><button onClick={e=>add(p.id,e)}><Plus/></button></article>)}</div></>}
{screen==='menu'&&<><div className="categoryHero"><h1>{cat}</h1><span>{cat==='Hamburguesas'?'CARNE, SABOR Y ACTITUD':'TRADICIÓN QUE NUNCA FALLA'}</span></div><div className="rows">{filtered.map(p=><ProductRow p={p} add={add} setSelected={setSelected}/>)}</div></>}
</main>{selected&&<Detail p={selected} close={()=>setSelected(null)} add={add} sub={sub} qty={cart[selected.id]||1}/>}</Shell>}
function ProductRow({p,add,setSelected}){return <article className="productRow" onClick={()=>setSelected(p)}><img src={p.img}/><div><b>{p.name}</b><p>{p.desc}</p><strong>{money(p.price)}</strong></div><button onClick={e=>add(p.id,e)}><Plus/></button></article>}
function Shell({children,screen,setScreen,count}){return <div className="page">{children}<nav className="bottomNav"><button className={screen==='home'?'on':''} onClick={()=>setScreen('home')}><Home/><span>Inicio</span></button><button className={screen==='menu'?'on':''} onClick={()=>setScreen('menu')}><Grid2X2/><span>Menú</span></button><button className={screen==='search'?'on':''} onClick={()=>setScreen('search')}><Search/><span>Buscar</span></button><button className={screen==='cart'?'on':''} onClick={()=>setScreen('cart')}><ShoppingCart/><span>Pedido</span>{count>0&&<i>{count}</i>}</button></nav></div>}
function Detail({p,close,add,sub,qty}){return <div className="detail"><div className="detailPhoto"><img src={p.img}/><button onClick={close}><ArrowLeft/></button><button className="heart"><Heart/></button><div className="sticker">LA CLÁSICA<br/>NUNCA FALLA</div></div><div className="detailBody"><div><h1>{p.name}</h1><b>{money(p.price)}</b></div><p>{p.desc}</p><h3>Personaliza tu hamburguesa</h3><section><button>Tipo de carne <span>Normal⌄</span></button><button>Extras <span>0 seleccionados⌄</span></button><button>Salsas <span>0 seleccionadas⌄</span></button></section></div><div className="detailBottom"><div><button onClick={e=>sub(p.id,e)}><Minus/></button><b>{qty}</b><button onClick={e=>add(p.id,e)}><Plus/></button></div><button onClick={e=>{add(p.id,e);close()}}>Agregar<br/>{money(p.price)}</button></div></div>}
function Cart({cart,data,add,sub,note,setNote,subtotal,delivery,total,setScreen}){const items=data.filter(p=>cart[p.id]);return <div className="cartPage"><div className="cartHead"><h1>Tu Pedido</h1><button onClick={()=>setScreen('home')}><X/></button></div>{items.map(p=><div className="cartItem"><img src={p.img}/><div><b>{p.name}</b><strong>{money(p.price)}</strong><div><button onClick={e=>sub(p.id,e)}><Minus/></button><span>{cart[p.id]}</span><button onClick={e=>add(p.id,e)}><Plus/></button></div></div><Trash2/></div>)}<label className="cartNote"><b>Agregar una nota</b><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Ej: sin cebolla, extra salsa, etc."/></label><div className="totals"><p><span>Subtotal</span><b>{money(subtotal)}</b></p><p><span>Costo de envío</span><b>{money(delivery)}</b></p><p><strong>Total</strong><strong>{money(total)}</strong></p></div><button className="finish" onClick={()=>setScreen('confirm')}>Finalizar pedido →</button><h3>También te podría gustar</h3><div className="upsell">{data.filter(p=>['Papas','Bebidas'].includes(p.cat)&&!cart[p.id]).slice(0,3).map(p=><article><img src={p.img}/><b>{p.name}</b><span>{money(p.price)}</span><button onClick={e=>add(p.id,e)}><Plus/></button></article>)}</div></div>}
createRoot(document.getElementById('root')).render(<App/>);