import React,{useMemo,useState}from'react';import{createRoot}from'react-dom/client';import{Menu,Search,ShoppingCart,Clock,MapPin,Bike,Package,Plus,Minus,X,ChevronRight,ArrowLeft,Trash2,Flame}from'lucide-react';import'./style.css';
const cats=['Hamburguesas','Completos','Papas','Bebidas','Promos'];
const data=[
{id:1,cat:'Hamburguesas',name:'Clásica',desc:'Carne, queso cheddar, lechuga, tomate, cebolla y salsa de la casa.',price:6500,img:'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=700&q=90'},
{id:2,cat:'Hamburguesas',name:'Doble',desc:'Doble carne, doble queso, lechuga, tomate, cebolla y salsa de la casa.',price:8500,img:'https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=700&q=90'},
{id:3,cat:'Hamburguesas',name:'Bacon',desc:'Carne, queso cheddar, tocino crujiente, cebolla crispy y salsa BBQ.',price:7900,img:'https://images.unsplash.com/photo-1594212699903-ec8a3eca50f5?auto=format&fit=crop&w=700&q=90'},
{id:4,cat:'Hamburguesas',name:'Especial',desc:'Carne, queso, tocino, huevo, lechuga, tomate, cebolla y salsa de la casa.',price:8900,img:'https://images.unsplash.com/photo-1571091718767-18b5b1457add?auto=format&fit=crop&w=700&q=90'},
{id:5,cat:'Completos',name:'Italiano',desc:'Vienesa, tomate, palta y mayo casera.',price:4900,img:'https://images.unsplash.com/photo-1612392062631-94dd858cba88?auto=format&fit=crop&w=700&q=90'},
{id:6,cat:'Papas',name:'Papas grandes',desc:'Papas fritas doradas y crujientes para compartir.',price:3500,img:'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?auto=format&fit=crop&w=700&q=90'},
{id:7,cat:'Bebidas',name:'Bebida en lata',desc:'Elige entre los sabores disponibles.',price:2000,img:'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&w=700&q=90'},
{id:8,cat:'Promos',name:'Combo Doble',desc:'Hamburguesa Doble + papas + bebida.',price:11900,img:'https://images.unsplash.com/photo-1594212699903-ec8a3eca50f5?auto=format&fit=crop&w=700&q=90'}];
const money=n=>'$'+n.toLocaleString('es-CL');
function App(){const[cat,setCat]=useState('Hamburguesas'),[q,setQ]=useState(''),[cart,setCart]=useState({}),[open,setOpen]=useState(false),[note,setNote]=useState('');
const add=id=>setCart(c=>({...c,[id]:(c[id]||0)+1})),sub=id=>setCart(c=>({...c,[id]:Math.max(0,(c[id]||0)-1)})),remove=id=>setCart(c=>({...c,[id]:0}));
const count=Object.values(cart).reduce((a,b)=>a+b,0),subtotal=data.reduce((s,p)=>s+(cart[p.id]||0)*p.price,0),delivery=count?2000:0,total=subtotal+delivery;
const shown=useMemo(()=>data.filter(p=>p.cat===cat&&(!q||p.name.toLowerCase().includes(q.toLowerCase())||p.desc.toLowerCase().includes(q.toLowerCase()))),[cat,q]);
return <div className="page"><header><button><Menu/></button><div className="brand"><strong>'ONDE EL CHUCKY</strong><span>STREET FOOD</span></div><div className="headActions"><button><Search/></button><button className="cartIcon" onClick={()=>setOpen(true)}><ShoppingCart/>{count>0&&<i>{count}</i>}</button></div></header>
<section className="hero"><img src="https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=1200&q=92"/><div className="scribble">COMIDA<br/>REAL<br/>SIN DRAMA</div></section>
<main><section className="status"><div><b><span className="dot"/>Abierto</b><small>12:00 – 23:30</small></div><div><MapPin/><p><b>San Javier</b><small>Retiro y delivery</small></p></div></section>
<section className="service"><div><Clock/><p><b>25–40 min</b><small>Tiempo estimado</small></p></div><div><Bike/><p><b>Delivery</b><small>En tu zona</small></p></div><div><Package/><p><b>Retiro</b><small>Sin costo</small></p></div></section>
<section className="promo"><div><b>PAPAS GRANDES</b><em>GRATIS</em><span>En compras sobre $15.000</span></div><img src="https://images.unsplash.com/photo-1573080496219-bb080dd4f877?auto=format&fit=crop&w=500&q=90"/><ChevronRight/></section>
<h2>Nuestro Menú</h2><nav className="categories">{cats.map(c=><button className={cat===c?'active':''} onClick={()=>setCat(c)}><span>{c==='Hamburguesas'?'🍔':c==='Completos'?'🌭':c==='Papas'?'🍟':c==='Bebidas'?'🥤':'%'}</span><small>{c}</small></button>)}</nav>
<label className="searchBox"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder={'Buscar en '+cat.toLowerCase()}/></label>
<div className="sectionHead"><h2>{cat}</h2><span>{shown.length} producto{shown.length!==1?'s':''}</span></div><section className="products">{shown.map(p=><article><img src={p.img}/><div><h3>{p.name}</h3><p>{p.desc}</p><b>{money(p.price)}</b></div>{cart[p.id]?<div className="step"><button onClick={()=>sub(p.id)}><Minus/></button><strong>{cart[p.id]}</strong><button onClick={()=>add(p.id)}><Plus/></button></div>:<button className="add" onClick={()=>add(p.id)}><Plus/></button>}</article>)}</section></main>
<footer><strong>'ONDE EL CHUCKY</strong><span>Buena comida, mejores momentos.</span></footer>
{count>0&&<button className="cartBar" onClick={()=>setOpen(true)}><span><ShoppingCart/>{count}</span><strong>Ver pedido</strong><b>{money(subtotal)}</b><ChevronRight/></button>}
{open&&<div className="overlay" onClick={()=>setOpen(false)}><aside onClick={e=>e.stopPropagation()}><div className="drawerTop"><div className="handle"/><button onClick={()=>setOpen(false)}><X/></button><h2>Tu Pedido</h2></div>{count===0?<div className="empty">Tu carrito está vacío.</div>:<>{data.filter(p=>cart[p.id]).map(p=><div className="cartLine"><img src={p.img}/><div><b>{p.name}</b><strong>{money(p.price)}</strong><div className="qty"><button onClick={()=>sub(p.id)}><Minus/></button><span>{cart[p.id]}</span><button onClick={()=>add(p.id)}><Plus/></button></div></div><button className="trash" onClick={()=>remove(p.id)}><Trash2/></button></div>)}<label className="note"><b>Agregar una nota</b><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Ej: sin cebolla, extra salsa, etc."/></label><div className="totals"><p><span>Subtotal</span><b>{money(subtotal)}</b></p><p><span>Costo de envío</span><b>{money(delivery)}</b></p><p className="grand"><span>Total</span><b>{money(total)}</b></p></div><button className="checkout">Finalizar pedido <ChevronRight/></button><h3 className="suggestTitle">También te podría gustar</h3><div className="suggest">{data.filter(p=>['Papas','Bebidas'].includes(p.cat)&&!cart[p.id]).slice(0,3).map(p=><article><img src={p.img}/><b>{p.name}</b><span>{money(p.price)}</span><button onClick={()=>add(p.id)}><Plus/></button></article>)}</div><div className="good">♡ &nbsp; Buena comida, mejores momentos</div></>}</aside></div>}</div>}
createRoot(document.getElementById('root')).render(<App/>);